### ISSUE TITLE
咨询: 我一直不太明白给这种工具类东西做成Docker, 一般用在哪呢, 求解惑

### ISSUE THREAD

**Issue by cryzlasm** [imWildCat/vscode-docker#1]
咨询: 我一直不太明白给这种工具类东西做成Docker, 一般用在哪呢, 求解惑

**Comment by MikeChongCan** [comment]
https://www.zhihu.com/question/22871084

**Comment by cryzlasm** [comment]
Docker 我知道啥意思,  我是说给 vscode  放在 docker 里边 这个作用是啥呢? 
就比如给 vim 放在docker里边 作用是啥呢?

比如说会发挥 docker-vscode 里边什么特性?

**Comment by MikeChongCan** [comment]
@cryzlasm vscode 最新版本里支持了 `yarn web` 这个命令以在云端运行。这个 repo 做一下类似 https://github.com/cdr/code-server 的实现，只是玩具，不用当真。

**Comment by cryzlasm** [comment]
好的, 谢谢.  关了吧
